name: deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0    # for mkdocs-git-revision-date-localized-plugin
    
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12.4
    
      - run: pip install -r requirements.txt
    
      - name: Create CNAME file
        run: echo "www.eestudy.com.cn" > docs/CNAME   # Adjust the path if your configuration is different
    
      - name: Deploy with MkDocs
        # run: export JUPYTER_PLATFORM_DIRS=1 && export MKDOCS_GIT_COMMITTERS_APIKEY=${{ secrets.MKDOCS_GIT_COMMITTERS_APIKEY }} && 
        run: mkdocs gh-deploy --force