# .github/workflows/ssh-upload.yml
# 将gh-pages分支的文件上传到服务器
name: upload-to-server

on:
  push:
    branches:
      - gh-pages

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Deploy to Server via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./"
          target: "/www/eestudy"   # 修改为你的服务器路径
